image: node:8.4.0
pages:
  stage: deploy
  environment:
    name: production
    url: https://johnsardine.gitlab.io/unbabel-mobile-challenge/
  script:
  - npm install
  - npm run build
  - mkdir .public
  - cp -r dist/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
