rules:
  class-name-format:
    - 2
    - convention: ^([\&,\.]*)[A-z](\-?[A-z0-9]+)*(__[A-z0-9](\-?[A-z0-9]+)*)?((_[A-z0-9](\-?[A-z0-9]+)*){0,2})?$
    - convention-explanation: Figure it out, biatch
  variable-name-format:
    - 2
    - convention: ^([\&,\.]*)[A-z](\-?[A-z0-9]+)*(__[A-z0-9](\-?[A-z0-9]+)*)?((_[A-z0-9](\-?[A-z0-9]+)*){0,2})?$
    - convention-explanation: Figure it out, biatch
  placeholder-name-format:
    - 2
    - convention: ^([\&,\.]*)[A-z](\-?[A-z0-9]+)*(__[A-z0-9](\-?[A-z0-9]+)*)?((_[A-z0-9](\-?[A-z0-9]+)*){0,2})?$
    - convention-explanation: Figure it out, biatch
